### ISSUE TITLE
Déploiement de la V2 de Nantral Platform en React

### ISSUE THREAD

**Issue by hydrielax** [3cn-ecn/nantralPlatform#1008]
Choses à faire avant de pouvoir merger la v2 (branche react-app) sur master : 

### Interface
- [x] Menu principal : ouverture du menu trop lente sur mobile (supprimer le delay de l'animation ?)
- [x] Supprimer "Accueil" dans le fil d'Ariane (sauf sur la page d'accueil, optionnellement) #1017 
- [x] Ombre sur le hover des icônes notif et profil à réduire (comme pour l'icône menu)
- [x] Corriger les imports svg
    - [x] Réutiliser les svg originaux non-modifiés
    - [x] Remodifier le svg de l'icône Home
    - [x] Ajouter des fonctions d'isolation CSS pour éviter que les SVG aient les propriétés CSS extérieures
 - [x] Corriger les erreurs dans les notifications
   - [x] Rediriger vers le lien correct pour les évènements #1017 
   - [x] Traiter le cas des posts #1017
   - [x] Corriger l'apparition des notifications pour un post privé 

### Events
- [x] Image par défaut pour les events : utiliser [cette image](https://drive.google.com/file/d/1In_ezsyJSnF8vIDTci9o-zP-bLkwnXbe/view?usp=share_link)
- [x] Formulaire d'ajout d'event fonctionnel #1017 
- [x] Bouton "Tous les events" sur la page d'accueil dans la section events qui redirige vers la page events #1017
- [x] Design du calendrier (boutons, grille plus light)

### Profils
- [ ] Supprimer les anciennes pages profils
- [x] #1024

### Refacto du Code
- [x] Supprimer tous les fichiers SCSS (utiliser plutôt le stylage MUI avec la fonction `styled`)
- [x] Supprimer tous les `const { ... } = props` => regarder comme exemple ce qui est fait pour la page Event (les composants dans `view`)
- [x] Renommer les types des objets sans le suffixe `Props` (réservé aux types des composants React)
- [x] Réintégrer dans le dossier de la page les composants qui ne concernent qu'une page, plutôt que de les mettre dans composants (exemple : calendrier)
- [x] Ajouter les tests de lint, types et jest dans les commandes du package.json et dans le CI
- [x] Exporter tous les appels d'api dans des hooks du type `useEventQuery` basés sur le `useQuery` ou `useMutation` de react-query, et réunir ces hooks customs dans un fichier `events.queries.ts` par exemple dans le dossier de chaque page.

**Comment by hydrielax** [comment]
Choses qui resteront à faire mais pour une prochaine mise à jour : 
* page des groupes
* page d'annuaire étudiant
* page d'édition du profil
* design page event
* design notifications
