### ISSUE TITLE
Améliorer les events

### ISSUE THREAD

**Issue by hydrielax** [3cn-ecn/nantralPlatform#742]
- [x] Ajouter une image par défaut pour les events sans image (cf #605)
- [x] Corriger le bug du nom de l'image de l'event fixé à "None" lors de la première sauvegarde (cf #635)
- [x] Autoriser tous les formats d'images et pas seulement des bannières
- [x] Demander une date/heure de fin pour chaque event (cf #882)
- [ ] Autoriser l'ajout de tags @ ou # dans la description
- [x] Créer une page avec la liste de tous les events (cf #963)
- [x] Créer un calendrier automatiquement généré avec tous les events et des options de filtrage (cf #862)
- [ ] Autoriser l'export d'event pour pouvoir les ajouter dans son agenda perso (cf #916)
- [x] Autoriser plusieurs moyens d'inscriptions à un event : (cf #856, #858, #885)
    - [x] Inscrption directe par le bouton "Je participe !" (moyen actuel)
    - [x] Inscription avec bouton shotgun (cf #531)
    - [x] Inscription avec un bouton redirigeant vers un google form ou tout autre lien
