### ISSUE TITLE
[TICKET] Fusionner les tables User et Student

### ISSUE THREAD

**Issue by hydrielax** [3cn-ecn/nantralPlatform#787]
# Description

Problème : on utilise actuellement la table `User` par défaut de django, avec une table secondaire `Student` pour compléter les champs qui nous manque. Cela complique inutilement le code pour ajouter des fonctionnalités, mais pose aussi beaucoup de problèmes pour les comptes temporaires, la réinitialisation de mdp, etc...

Solution : supprimer la table `User` par défaut de django et créer la notre à la place, qui hérite du `BaseUser` de django.

# Definition of Done

- [x] J'ai une table unique `User` #1095
- [ ] Les informations de profils (picture, promo...) sont stockées soit dans la table User, soit dans une table Profile (mais dans tous les cas supprimer ou au moins renommer la table Student)
- [x] Le champ email est marqué comme unique #1095
- [x] Le champ username est marqué comme unique #1095
- [x] #1323
- [x] Le mail peut-être modifié (pour quand on part de Centrale) #1329 

# Strat technique

https://docs.djangoproject.com/en/4.2/topics/auth/customizing/#changing-to-a-custom-user-model-mid-project

**Comment by hydrielax** [comment]
@rravelli Quelques infos en plus qui pourraient t'être utiles :
Pour exécuter une commande SQL directement sur la database, tu peux déjà tester en local en utilisant docker-compose en local (ya une page dessus dans la doc). Ensuite pour exécuter une commande SQL, il faut ouvrir un shell dans le service database (là je sais plus la commande mais ça se retrouve) et tu devrais pouvoir exécuter du SQL.
En prod, attention : il faudra utiliser les mêmes commandes, mais en remplaçant `docker compose` par `dcf` (si tu lances une commande avec docker-compose ça va utiliser le docker compose de dev au lieu de prod et je te racontes pas les dégâts que ça peut faire...)
Et sinon en local si tu fais tourner ta base de données postgres avec docker tu peux y accéder dans pgAdmin4
