### ISSUE TITLE
Create event calendar

### ISSUE THREAD

**Issue by ErwanQui** [3cn-ecn/nantralPlatform#862]
- [x] Créer le template du calendrier (cf #855, #861)
- [x] Récupérer les events (cf #889)
- [x] Afficher les events au bon endroit, le bon jour (cf #875)
- [x] Permettre un affichage d'events qui ont lieu en même temps (cf #888)
- [x] Changer l'affichage des events en fonction de leurs caractéristiques (cf #987, #1001)
- [x] Rendre l'affichage optimal (cf #914, #915)
- [x] Permettre de switcher entre différentes périodes de temps (cf #890)
- [x] Lier les blocs events du calendrier aux events (cf #996)
- [x] #929
- [x] Exporter le calendrier (cf #916)
- [x] Vérifier l'intégration sur mobile (cf #913)
- [x] Add some tests (cf #935, #954)
- [x] Internationalisation (cf #1028)
- [x] Adapter les noms des variables pour plus de cohérence

**Comment by ErwanQui** [comment]
There isn't any test on the calendar component itself at the moment #1000
