### ISSUE TITLE
Implement frontend tests

### ISSUE THREAD

**Issue by ErwanQui** [3cn-ecn/nantralPlatform#950]
- [x] Do work local tests (cf #935)
- [x] Do work test in github (cf #946 #948)
- [x] Update coverage in sonarcloud (cf #949)
